### PR TITLE
Accept style as cli arg 

### LINKED ISSUE #127: accept style as cli arg to launch.sh
We shouldn't be editing this repo after cloning just to select the style.

Lets accept it as a cli arg: 

```shell
~/.config/rofi/launchers/type-1/launch.sh style-3
```

### PR DESCRIPTION
**Pull request by airtonix**
fixes #127

### CODE REVIEW

**Review by victor-heliomar — APPROVED** [review]
LGTM. Can you add a little explanation about how to use your changes?

**Comment by leegenes** [comment]
Not a maintainer, but stumbled on this, and would probably argue in favor of leaving the `*/files/launchers/launcher.sh` files as they are (with hopes to remove them at some point in the future).

In its simplest form because I am not at all confident with bash and will need to take a minute to get myself up to speed on it, thinking something like `rofi/files/launcher.sh`:
```
dir="$HOME/.config/rofi/launchers/type-$1"
theme="style-$2"

rofi \
    -show drun \
    -theme ${dir}/${theme}.rasi
```

Could move toward deprecating need for a launcher per "type" if introducing releases.

**Comment by julian-poidevin** [comment]
@airtonix Could you add documentation ?

**Comment by julian-poidevin** [comment]
@victor-heliomar I also could form from @airtonix branch, and add the required documentation, I'm really interested on that feature.

**Comment by victor-heliomar** [comment]
@julian-poidevin maybe create another PR with the doc and I think this could be merged

Seems like in issue #127 description is a way to use it, only needs to be tested
image

What do you think?

**Comment by julian-poidevin** [comment]
> @julian-poidevin maybe create another PR with the doc and I think this could be merged
> 
> Seems like in issue #127 description is a way to use it, only needs to be tested image
> 
> What do you think?

On my fork, I merged this PR and it's working as expected.
I'll create a branch of @airtonix branch to add documentation on how to use the cli and open a new PR here.
I hope @airtonix doesn't mind.

**Pull request closed without merging**
