### PR TITLE
Made the hostname variable UNIX-universal

### PR DESCRIPTION
**Pull request by Mattio-cmd**
Not all unix and unix-like operating systems have `hostname` command installed by default. I used the standard `uname` with the `-a` flag and then i did some basic text processing with awk.

### CODE REVIEW

**Comment by lebensterben** [comment]
- Not all system has awk.
- `uname -a | awk` is unnecessary, just use `uname -n`

**Comment by Mattio-cmd** [comment]
> * Not all system has awk.

Which systems does not have awk?

**Comment by lebensterben** [comment]
google "awk command not found" and you will see thousands of people struggling with this.

**Comment by Mattio-cmd** [comment]
There, i changed it to `uname -n`

**Pull request closed without merging**
